services:
  main-chain-node:
    container_name: main-chain-node
    image: bosagora/agora-el-node:v2.0.1
    ports:
      - "8540:8545"
    restart: always
    volumes:
      - ../main-chain/chain:/data
      - ../main-chain/config:/config
    command:
      --config=/config/config.toml
      --networkid=24600
      --datadir=/data
      --syncmode=full
      --gcmode=archive
      --allow-insecure-unlock=true
      --unlock=0xF85B2dbA83A08DEe6E24E4461E0334e7384896F9
      --password=/config/private/password.txt
      --mine=true
      --miner.etherbase=0xF85B2dbA83A08DEe6E24E4461E0334e7384896F9
      --http.corsdomain="*"
    networks:
      - bosagora_network

networks:
  bosagora_network:
    driver: bridge
    external: true
    internal: true

